import type { Metadata } from "next";
import "../styles/globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import {Geist, Geist_Mono ,Roboto ,Bungee_Shade, Inter, Galdeano, DM_Sans, Poppins } from "next/font/google";
import LayoutShell from "@/components/LayoutShell";

const lemon = localFont({
  src: [
    { path: "../public/fonts/Lemon-Regular.ttf", weight: "400", style: "normal" },
  ],
  variable: "--font-lemon",
  display: "swap",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-roboto",
  display: "swap",
});

const bungeeShade = Bungee_Shade({ subsets: ["latin"], weight: "400", variable: "--font-bungee-shade" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const galdeano = Galdeano({ weight: "400", subsets: ["latin"], variable: "--font-galdeano" });
const dmSans   = DM_Sans({ subsets: ["latin"], variable: "--font-dm-sans" });
const poppins  = Poppins({ weight: ["400","500","600"], subsets: ["latin"], variable: "--font-poppins" });



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${lemon.variable} ${roboto.variable} ${bungeeShade.variable} ${inter.variable} ${galdeano.variable} ${dmSans.variable} ${poppins.variable}`} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        style={{background:"fffffff" }}
      >
        {/*<div className="bg-gradient-to-r from-[#15443d] via-[#417b72] to-[#165046]">
          <Navbar/>
          
        {children}
        <Footer/>
  </div>*/}
  <div className="bg-gradient-to-r from-[#14403B] via-[#306C67] to-[#103B37]">
  <LayoutShell>{children}</LayoutShell>
  </div>

      </body>
    </html>
  );
}
